zuozhe: 'QQ：1628708538'
#支持多个用户签到
lin:
  #第一个用户
  - user:
        # openId自己获取
        openId: ''
        # qmsg消息推送：https://qmsg.zendee.cn/ 自己注册获取key
        qmsg: ''
        #课堂评教内容
        pingjiao: 'nice'
  #第二个用户
  - user:
        # openId自己获取
        openId: '' 
        # qmsg消息推送：https://qmsg.zendee.cn/ 自己注册获取key
        qmsg: ''
        #课堂评教内容
        pingjiao: 'nice'
