zuozhe: 'QQ：1628708538'
#支持多个用户签到
lin:
  #第一个用户
  - user:
        # openId自己获取
        openId: 'o8l2QuEhu6PPwVYlvBcHuTDdPA_c'
        # qmsg消息推送：https://qmsg.zendee.cn/ 自己注册获取key
        qmsg: '3f42622c52182f5235710227c7068ba5'
        #课堂评教内容
        pingjiao: '教师通过对文章的独到深入的讲解，达到了很好的教学效果，知识系统深入，并能结合多种教学手段，使学生对知识的掌握更深刻。教学内容重点突出，教学目的十分明确，语言流畅，通俗易懂，立意新颖，能够吸引学生听课的注意力，并与学生有较多的互动、激发学生的思维与学习兴趣'
  #第二个用户
  - user:
        # openId自己获取
        openId: 'o8l2QuGzzf4_7m9l8e8UjwGJA6Bk' 
        # qmsg消息推送：https://qmsg.zendee.cn/ 自己注册获取key
        qmsg: '3f42622c52182f5235710227c7068ba5'
        #课堂评教内容
        pingjiao: '老师教学认真，课堂效率高，授课资料详细，我们学生大部分都能跟着老师思路学习，气氛活跃，整节课学下来有收获欣喜，使人对此门课程兴趣浓厚。'